#!/bin/bash
resize -s 30 110  > /dev/null 2>&1
clear
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo "OOOOOOOOOOOOOOOOOOOOOO"
echo "OOOOOOOOOOOOOOOOOOOOOO"
sleep 0.1
clear
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo "     OOOOOOOOOOOOOOOOOOOOOO"
echo "     OOOOOOOOOOOOOOOOOOOOOO"
sleep 0.1
clear
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo "        OOOOOOOOOOOOOOOOOOOOOO"
echo "        OOOOOOOOOOOOOOOOOOOOOO"
sleep 0.1
clear
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo "           OOOOOOOOOOOOOOOOOOOOOO"
echo "           OOOOOOOOOOOOOOOOOOOOOO"
sleep 0.1
clear
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo "               OOOOOOOOOOOOOOOOOOOOOO"
echo "               OOOOOOOOOOOOOOOOOOOOOO"
sleep 0.1
clear
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo "                  OOOOOOOOOOOOOOOOOOOOOO"
echo "                  OOOOOOOOOOOOOOOOOOOOOO"
sleep 0.1
clear
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo "                     OOOOOOOOOOOOOOOOOOOOOO"
echo "                     OOOOOOOOOOOOOOOOOOOOOO"
sleep 0.1
clear
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo "                         OOOOOOOOOOOOOOOOOOOOOO"
echo "                         OOOOOOOOOOOOOOOOOOOOOO"
sleep 0.1
clear
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo "                             OOOOOOOOOOOOOOOOOOOOOO"
echo "                             OOOOOOOOOOOOOOOOOOOOOO"
sleep 0.1
clear
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo "                                OOOOOOOOOOOOOOOOOOOOOO"
echo "                                OOOOOOOOOOOOOOOOOOOOOO"
sleep 0.1
clear
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo "                                   OOOOOOOOOOOOOOOOOOOOOO"
echo "                                   OOOOOOOOOOOOOOOOOOOOOO"
sleep 0.1
clear
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo "                                         OOOOOOOOOOOOOOOOOOOOOO"
echo "                                         OOOOOOOOOOOOOOOOOOOOOO"
sleep 0.1
clear
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo "                                               OOOOOOOOOOOOOOOOOOOOOO"
echo "                                               OOOOOOOOOOOOOOOOOOOOOO"
sleep 0.1
clear
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo "                                                     OOOOOOOOOOOOOOOOOOOOOO"
echo "                                                     OOOOOOOOOOOOOOOOOOOOOO"
sleep 0.1
clear
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo "                                                                        OOO"
echo "                                                                          OOO "
echo "                                                                           OOO "
echo "                                                           OOOOOOOOOOOOOOOOOOO"
echo "                                                           OOOOOOOOOOOOOOOOOO"
sleep 0.1
clear
echo ""
echo ""
echo ""
echo ""
echo ""
echo "                                                                     OOO"
echo "                                                                     OOO"
echo "                                                                     OOO"
echo "                                                                      OOO"
echo "                                                                        OOO"
echo "                                                                          OOO "
echo "                                                                           OOO "
echo "                                                               OOOOOOOOOOOOOOO"
echo "                                                               OOOOOOOOOOOOOO"
sleep 0.1
clear
echo ""
echo ""
echo ""
echo ""
echo ""
echo "                                                                      OOOOOOOO"
echo "                                                                     OOOOOOOOO"
echo "                                                                     OOO"
echo "                                                                      OOO"
echo "                                                                        OOO"
echo "                                                                          OOO "
echo "                                                                           OOO "
echo "                                                                     OOOOOOOOO"
echo "                                                                     OOOOOOOO"
sleep 0.1
clear
echo ""
echo ""
echo ""
echo ""
echo ""
echo "                                                                      OOOOOOOO"
echo "                                                                     OOOOOOOOO"
echo "                                                                     OOO"
echo "                                                                      OOO"
echo "                                                                        OOO"
echo "                                                                          OOO "
echo "                                                                           OOO "
echo "                                                                     OOOOOOOOO"
echo "                                                        OOO     OOO  OOOOOOOO"
sleep 0.1
clear
echo ""
echo ""
echo ""
echo ""
echo ""
echo "                                                                      OOOOOOOO"
echo "                                                                     OOOOOOOOO"
echo "                                                                     OOO"
echo "                                                                      OOO"
echo "                                                                        OOO"
echo "                                                                          OOO "
echo "                                                        OOO     OOO        OOO "
echo "                                                        OOO     OOO  OOOOOOOOO"
echo "                                                        OOO     OOO  OOOOOOOO"
sleep 0.1
clear
echo ""
echo ""
echo ""
echo ""
echo ""
echo "                                                                      OOOOOOOO"
echo "                                                                     OOOOOOOOO"
echo "                                                                     OOO"
echo "                                                                      OOO"
echo "                                                        OOO     OOO     OOO"
echo "                                                        OOO     OOO       OOO "
echo "                                                        OOO     OOO        OOO "
echo "                                                        OOO     OOO  OOOOOOOOO"
echo "                                                        OOO     OOO  OOOOOOOO"
sleep 0.1
clear
echo ""
echo ""
echo ""
echo ""
echo ""
echo "                                                                      OOOOOOOO"
echo "                                                                     OOOOOOOOO"
echo "                                                        OOO     OOO  OOO"
echo "                                                        OOO     OOO   OOO"
echo "                                                        OOO     OOO     OOO"
echo "                                                        OOO     OOO       OOO "
echo "                                                        OOO     OOO        OOO "
echo "                                                        OOO     OOO  OOOOOOOOO"
echo "                                                        OOO     OOO  OOOOOOOO"
sleep 0.1
clear
echo ""
echo ""
echo ""
echo ""
echo ""
echo "                                                         OOOO OOOO    OOOOOOOO"
echo "                                                        OOOOO OOOOO  OOOOOOOOO"
echo "                                                        OOO     OOO  OOO"
echo "                                                        OOO     OOO   OOO"
echo "                                                        OOO     OOO     OOO"
echo "                                                        OOO     OOO       OOO "
echo "                                                        OOO     OOO        OOO "
echo "                                                        OOO     OOO  OOOOOOOOO"
echo "                                                        OOO     OOO  OOOOOOOO"
sleep 0.1
clear
echo ""
echo ""
echo ""
echo ""
echo ""
echo "                                                         OOOOOOOOO    OOOOOOOO"
echo "                                                        OOOOOOOOOOO  OOOOOOOOO"
echo "                                                        OOO OOO OOO  OOO"
echo "                                                        OOO  O  OOO   OOO"
echo "                                                        OOO     OOO     OOO"
echo "                                                        OOO     OOO       OOO "
echo "                                                        OOO     OOO        OOO "
echo "                                                        OOO     OOO  OOOOOOOOO"
echo "                                                        OOO     OOO  OOOOOOOO"
sleep 0.1
clear
echo ""
echo ""
echo ""
echo ""
echo ""
echo "                                                         OOOOOOOOO    OOOOOOOO"
echo "                                                        OOOOOOOOOOO  OOOOOOOOO"
echo "                                                        OOO     OOO  OOO"
echo "                                                        OOO     OOO   OOO"
echo "                                                        OOO  OO OOO     OOO"
echo "                                                        OOO OOO OOO       OOO "
echo "                                                        OOO OO  OOO        OOO "
echo "                                                        OOO O   OOO  OOOOOOOOO"
echo "                                                        OOO     OOO  OOOOOOOO"
sleep 0.1
clear
echo ""
echo ""
echo ""
echo ""
echo ""
echo "                                                         OOOOOOOOO    OOOOOOOO"
echo "                                                        OOOOOOOOOOO  OOOOOOOOO"
echo "                                                        OOO     OOO  OOO"
echo "                                                        OOO     OOO   OOO"
echo "                                                        OOO     OOO     OOO"
echo "                                                        OOO     OOO       OOO "
echo "                                                        OOO     OOO        OOO "
echo "                                                        OOOOOOOOOOO  OOOOOOOOO"
echo "                                                         OOOOOOOOO   OOOOOOOO"
sleep 0.1
clear
echo "    O"
echo "    O"
echo "    O"
echo ""
echo "                                                         OOOOOOOOO    OOOOOOOO"
echo "                                                        OOOOOOOOOOO  OOOOOOOOO"
echo "                                                        OOO     OOO  OOO"
echo "                                                        OOO     OOO   OOO"
echo "                                                        OOO     OOO     OOO"
echo "                                                        OOO     OOO       OOO "
echo "                                                        OOO     OOO        OOO "
echo "                                                        OOOOOOOOOOO  OOOOOOOOO"
echo "                                                         OOOOOOOOO   OOOOOOOO"
sleep 0.1
clear
echo "  OOOOO"
echo "     "
echo "     "
echo "    O"
echo "    O                                                    OOOOOOOOO    OOOOOOOO"
echo "    O                                                   OOOOOOOOOOO  OOOOOOOOO"
echo "    O                                                   OOO     OOO  OOO"
echo "    O                                                   OOO     OOO   OOO"
echo "                                                        OOO     OOO     OOO"
echo "                                                        OOO     OOO       OOO "
echo "                                                        OOO     OOO        OOO "
echo "                                                        OOOOOOOOOOO  OOOOOOOOO"
echo "                                                         OOOOOOOOO   OOOOOOOO"
sleep 0.1
clear
echo "  OOOOO"
echo "  OOOOO"
echo "  OOOOO"
echo "  OOOOO"
echo "    O                                                    OOOOOOOOO    OOOOOOOO"
echo "    O                                                   OOOOOOOOOOO  OOOOOOOOO"
echo "    O                                                   OOO     OOO  OOO"
echo "    O                                                   OOO     OOO   OOO"
echo "    O                                                   OOO     OOO     OOO"
echo "                                                        OOO     OOO       OOO "
echo "                                                        OOO     OOO        OOO "
echo "                                                        OOOOOOOOOOO  OOOOOOOOO"
echo "                                                         OOOOOOOOO   OOOOOOOO"
sleep 0.1
clear
echo "  OOOOO"
echo "  OOOOO"
echo "  OOOOO"
echo "  OOOOO"
echo "  OOOOO                                                  OOOOOOOOO    OOOOOOOO"
echo " OO O OO                                                OOOOOOOOOOO  OOOOOOOOO"
echo "    O                                                   OOO     OOO  OOO"
echo "    O                                                   OOO     OOO   OOO"
echo "    O                                                   OOO     OOO     OOO"
echo "                                                        OOO     OOO       OOO "
echo "                                                        OOO     OOO        OOO "
echo "                                                        OOOOOOOOOOO  OOOOOOOOO"
echo "                                                         OOOOOOOOO   OOOOOOOO"
sleep 0.1
clear
echo "  OOOOO"
echo "  OOOOO"
echo "  OOOOO"
echo "  OOOOO"
echo "  OOOOO                                                  OOOOOOOOO    OOOOOOOO"
echo " OO O OO                                                OOOOOOOOOOO  OOOOOOOOO"
echo "OO  O  OO                                               OOO     OOO  OOO"
echo "OO  O  OO                                               OOO     OOO   OOO"
echo "    O                                                   OOO     OOO     OOO"
echo "                                                        OOO     OOO       OOO "
echo "                                                        OOO     OOO        OOO "
echo "                                                        OOOOOOOOOOO  OOOOOOOOO"
echo "                                                         OOOOOOOOO   OOOOOOOO"
sleep 0.1
clear
echo "  OOOOO"
echo "  OOOOO"
echo "  OOOOO"
echo "  OOOOO"
echo "  OOOOO                                                  OOOOOOOOO    OOOOOOOO"
echo " OO O OO                                                OOOOOOOOOOO  OOOOOOOOO"
echo "OO  O  OO                                               OOO     OOO  OOO"
echo "OO  O  OO                                               OOO     OOO   OOO"
echo "OO  O  OO                                               OOO     OOO     OOO"
echo "OO     OO                                               OOO     OOO       OOO "
echo "                                                        OOO     OOO        OOO "
echo "                                                        OOOOOOOOOOO  OOOOOOOOO"
echo "                                                         OOOOOOOOO   OOOOOOOO"
sleep 0.1
clear
echo ""
echo ""
echo "   OOO"
echo "  OOOOO"
echo "  OOOOO                                                  OOOOOOOOO    OOOOOOOO"
echo " OO O OO                                                OOOOOOOOOOO  OOOOOOOOO"
echo "OO  O  OO                                               OOO     OOO  OOO"
echo "OO  O  OO                                               OOO     OOO   OOO"
echo "OO  O  OO                                               OOO     OOO     OOO"
echo "OO     OO                                               OOO     OOO       OOO "
echo "OO     OO                                               OOO     OOO        OOO "
echo "OO     OO                                               OOOOOOOOOOO  OOOOOOOOO"
echo "                                                         OOOOOOOOO   OOOOOOOO"
sleep 0.1
clear
echo ""
echo ""
echo ""
echo "    O"
echo "   OOO                                                   OOOOOOOOO    OOOOOOOO"
echo "  OOOOO                                                 OOOOOOOOOOO  OOOOOOOOO"
echo " OO O OO                                                OOO     OOO  OOO"
echo "OO  O  OO                                               OOO     OOO   OOO"
echo "OO  O  OO                                               OOO     OOO     OOO"
echo "OO     OO                                               OOO     OOO       OOO "
echo "OO     OO                                               OOO     OOO        OOO "
echo "OO     OO                                               OOOOOOOOOOO  OOOOOOOOO"
echo "OO     OO                                                OOOOOOOOO   OOOOOOOO"
sleep 0.1
clear
echo ""
echo ""
echo ""
echo ""
echo "   OOO                                                   OOOOOOOOO    OOOOOOOO"
echo "  OO OO                                                 OOOOOOOOOOO  OOOOOOOOO"
echo " OO   OO                                                OOO     OOO  OOO"
echo "OO  O  OO                                               OOO     OOO   OOO"
echo "OO  O  OO                                               OOO     OOO     OOO"
echo "OO  O  OO                                               OOO     OOO       OOO "
echo "OO  O  OO                                               OOO     OOO        OOO "
echo "OO     OO                                               OOOOOOOOOOO  OOOOOOOOO"
echo "OO     OO                                                OOOOOOOOO   OOOOOOOO"
sleep 0.1
clear
echo ""
echo ""
echo ""
echo ""
echo "   OOO                                                   OOOOOOOOO    OOOOOOOO"
echo "  OO OO                                                 OOOOOOOOOOO  OOOOOOOOO"
echo " OO   OO                                                OOO     OOO  OOO"
echo "OO     OO                                               OOO     OOO   OOO"
echo "OOOOOOOOO                                               OOO     OOO     OOO"
echo "OO     OO                                               OOO     OOO       OOO "
echo "OO     OO                                               OOO     OOO        OOO "
echo "OO     OO                                               OOOOOOOOOOO  OOOOOOOOO"
echo "OO     OO                                                OOOOOOOOO   OOOOOOOO"
sleep 0.1
clear
echo ""
echo ""
echo ""
echo ""
echo "   OOO                                                   OOOOOOOOO    OOOOOOOO"
echo "  OO OO                                                 OOOOOOOOOOO  OOOOOOOOO"
echo " OO   OO                                                OOO     OOO  OOO"
echo "OO     OO                                               OOO     OOO   OOO"
echo "OOOOOOOOO                                               OOO     OOO     OOO"
echo "OO     OO                                               OOO     OOO       OOO "
echo "OO     OO                                               OOO     OOO        OOO "
echo "OO     OO                  OOO                          OOOOOOOOOOO  OOOOOOOOO"
echo "OO     OO                  OOO                           OOOOOOOOO   OOOOOOOO"
sleep 0.1
clear
echo ""
echo ""
echo ""
echo ""
echo "   OOO                                                   OOOOOOOOO    OOOOOOOO"
echo "  OO OO                                                 OOOOOOOOOOO  OOOOOOOOO"
echo " OO   OO                                                OOO     OOO  OOO"
echo "OO     OO                                               OOO     OOO   OOO"
echo "OOOOOOOOO                                               OOO     OOO     OOO"
echo "OO     OO                  OOO                          OOO     OOO       OOO "
echo "OO     OO                  OOO                          OOO     OOO        OOO "
echo "OO     OO                  OOO                          OOOOOOOOOOO  OOOOOOOOO"
echo "OO     OO                  OOO                           OOOOOOOOO   OOOOOOOO"
sleep 0.1
clear
echo ""
echo ""
echo ""
echo ""
echo "   OOO                                                   OOOOOOOOO    OOOOOOOO"
echo "  OO OO                                                 OOOOOOOOOOO  OOOOOOOOO"
echo " OO   OO                                                OOO     OOO  OOO"
echo "OO     OO                  OOO                          OOO     OOO   OOO"
echo "OOOOOOOOO                  OOO                          OOO     OOO     OOO"
echo "OO     OO                  OOO                          OOO     OOO       OOO "
echo "OO     OO                  OOO                          OOO     OOO        OOO "
echo "OO     OO                  OOO                          OOOOOOOOOOO  OOOOOOOOO"
echo "OO     OO                  OOO                           OOOOOOOOO   OOOOOOOO"
sleep 0.1
clear
echo ""
echo ""
echo ""
echo ""
echo "   OOO                                                   OOOOOOOOO    OOOOOOOO"
echo "  OO OO                                                 OOOOOOOOOOO  OOOOOOOOO"
echo " OO   OO                                                OOO     OOO  OOO"
echo "OO     OO                  OOO                          OOO     OOO   OOO"
echo "OOOOOOOOO                  OOO                          OOO     OOO     OOO"
echo "OO     OO                  OOO                          OOO     OOO       OOO "
echo "OO     OO                  OOO                          OOO     OOO        OOO "
echo "OO     OO                  OOO                          OOOOOOOOOOO  OOOOOOOOO"
echo "OO     OO                  OOO                           OOOOOOOOO   OOOOOOOO"
sleep 0.1
clear
echo ""
echo ""
echo ""
echo ""
echo "   OOO                                                   OOOOOOOOO    OOOOOOOO"
echo "  OO OO                    OOO                          OOOOOOOOOOO  OOOOOOOOO"
echo " OO   OO                   OOO                          OOO     OOO  OOO"
echo "OO     OO                  OOO                          OOO     OOO   OOO"
echo "OOOOOOOOO                  OOO                          OOO     OOO     OOO"
echo "OO     OO                  OOO                          OOO     OOO       OOO "
echo "OO     OO                  OOO                          OOO     OOO        OOO "
echo "OO     OO                  OOO                          OOOOOOOOOOO  OOOOOOOOO"
echo "OO     OO                  OOO                           OOOOOOOOO   OOOOOOOO"
sleep 0.1
clear
echo ""
echo ""
echo ""
echo ""
echo "   OOO                   OOOOOOO                         OOOOOOOOO    OOOOOOOO"
echo "  OO OO                  OOOOOOO                        OOOOOOOOOOO  OOOOOOOOO"
echo " OO   OO                   OOO                          OOO     OOO  OOO"
echo "OO     OO                  OOO                          OOO     OOO   OOO"
echo "OOOOOOOOO                  OOO                          OOO     OOO     OOO"
echo "OO     OO                  OOO                          OOO     OOO       OOO "
echo "OO     OO                  OOO                          OOO     OOO        OOO "
echo "OO     OO                  OOO                          OOOOOOOOOOO  OOOOOOOOO"
echo "OO     OO                  OOO                           OOOOOOOOO   OOOOOOOO"
sleep 0.1
clear
echo ""
echo ""
echo ""
echo ""
echo "   OOO                 OOOOOOOOOOO                       OOOOOOOOO    OOOOOOOO"
echo "  OO OO                OOOOOOOOOOO                      OOOOOOOOOOO  OOOOOOOOO"
echo " OO   OO                   OOO                          OOO     OOO  OOO"
echo "OO     OO                  OOO                          OOO     OOO   OOO"
echo "OOOOOOOOO                  OOO                          OOO     OOO     OOO"
echo "OO     OO                  OOO                          OOO     OOO       OOO "
echo "OO     OO                  OOO                          OOO     OOO        OOO "
echo "OO     OO                  OOO                          OOOOOOOOOOO  OOOOOOOOO"
echo "OO     OO                  OOO                           OOOOOOOOO   OOOOOOOO"
sleep 0.1
clear
echo ""
echo ""
echo ""
echo ""
echo "   OOO                 OOOOOOOOOOO                       OOOOOOOOO    OOOOOOOO"
echo "  OO OO                OOOOOOOOOOO                      OOOOOOOOOOO  OOOOOOOOO"
echo " OO   OO                   OOO                          OOO     OOO  OOO"
echo "OO     OO                  OOO                          OOO     OOO   OOO"
echo "OOOOOOOOO                  OOO                          OOO     OOO     OOO"
echo "OO     OO                  OOO                          OOO     OOO       OOO "
echo "OO     OO                  OOO                          OOO     OOO        OOO "
echo "OO     OO  OO              OOO                          OOOOOOOOOOO  OOOOOOOOO"
echo "OO     OO  OO              OOO                           OOOOOOOOO   OOOOOOOO"
sleep 0.1
clear
echo ""
echo ""
echo ""
echo ""
echo "   OOO                 OOOOOOOOOOO                       OOOOOOOOO    OOOOOOOO"
echo "  OO OO                OOOOOOOOOOO                      OOOOOOOOOOO  OOOOOOOOO"
echo " OO   OO                   OOO                          OOO     OOO  OOO"
echo "OO     OO                  OOO                          OOO     OOO   OOO"
echo "OOOOOOOOO  OO              OOO                          OOO     OOO     OOO"
echo "OO     OO  OO              OOO                          OOO     OOO       OOO "
echo "OO     OO  OO              OOO                          OOO     OOO        OOO "
echo "OO     OO  OO              OOO                          OOOOOOOOOOO  OOOOOOOOO"
echo "OO     OO  OO              OOO                           OOOOOOOOO   OOOOOOOO"
sleep 0.1
clear
echo ""
echo ""
echo ""
echo ""
echo "   OOO                 OOOOOOOOOOO                       OOOOOOOOO    OOOOOOOO"
echo "  OO OO                OOOOOOOOOOO                      OOOOOOOOOOO  OOOOOOOOO"
echo " OO   OO   OO              OOO                          OOO     OOO  OOO"
echo "OO     OO  OO              OOO                          OOO     OOO   OOO"
echo "OOOOOOOOO  OO              OOO                          OOO     OOO     OOO"
echo "OO     OO  OO              OOO                          OOO     OOO       OOO "
echo "OO     OO  OO              OOO                          OOO     OOO        OOO "
echo "OO     OO  OO              OOO                          OOOOOOOOOOO  OOOOOOOOO"
echo "OO     OO  OO              OOO                           OOOOOOOOO   OOOOOOOO"
sleep 0.1
clear
echo ""
echo ""
echo ""
echo ""
echo "   OOO     OOOOO       OOOOOOOOOOO                       OOOOOOOOO    OOOOOOOO"
echo "  OO OO    OO          OOOOOOOOOOO                      OOOOOOOOOOO  OOOOOOOOO"
echo " OO   OO   OO              OOO                          OOO     OOO  OOO"
echo "OO     OO  OO              OOO                          OOO     OOO   OOO"
echo "OOOOOOOOO  OO              OOO                          OOO     OOO     OOO"
echo "OO     OO  OO              OOO                          OOO     OOO       OOO "
echo "OO     OO  OO              OOO                          OOO     OOO        OOO "
echo "OO     OO  OO              OOO                          OOOOOOOOOOO  OOOOOOOOO"
echo "OO     OO  OO              OOO                           OOOOOOOOO   OOOOOOOO"
sleep 0.1
clear
echo ""
echo ""
echo ""
echo ""
echo "   OOO     OOOOOOOO    OOOOOOOOOOO                       OOOOOOOOO    OOOOOOOO"
echo "  OO OO    OOOOOOOOO   OOOOOOOOOOO                      OOOOOOOOOOO  OOOOOOOOO"
echo " OO   OO   OO              OOO                          OOO     OOO  OOO"
echo "OO     OO  OO              OOO                          OOO     OOO   OOO"
echo "OOOOOOOOO  OO              OOO                          OOO     OOO     OOO"
echo "OO     OO  OO              OOO                          OOO     OOO       OOO "
echo "OO     OO  OO              OOO                          OOO     OOO        OOO "
echo "OO     OO  OO              OOO                          OOOOOOOOOOO  OOOOOOOOO"
echo "OO     OO  OO              OOO                           OOOOOOOOO   OOOOOOOO"
sleep 0.1
clear
echo ""
echo ""
echo ""
echo ""
echo "   OOO     OOOOOOOO    OOOOOOOOOOO                       OOOOOOOOO    OOOOOOOO"
echo "  OO OO    OOOOOOOOO   OOOOOOOOOOO                      OOOOOOOOOOO  OOOOOOOOO"
echo " OO   OO   OO      OO      OOO                          OOO     OOO  OOO"
echo "OO     OO  OO      OO      OOO                          OOO     OOO   OOO"
echo "OOOOOOOOO  OO     OO       OOO                          OOO     OOO     OOO"
echo "OO     OO  OO              OOO                          OOO     OOO       OOO "
echo "OO     OO  OO              OOO                          OOO     OOO        OOO "
echo "OO     OO  OO              OOO                          OOOOOOOOOOO  OOOOOOOOO"
echo "OO     OO  OO              OOO                           OOOOOOOOO   OOOOOOOO"
sleep 0.1
clear
echo ""
echo ""
echo ""
echo ""
echo "   OOO     OOOOOOOO    OOOOOOOOOOO                       OOOOOOOOO    OOOOOOOO"
echo "  OO OO    OOOOOOOOO   OOOOOOOOOOO                      OOOOOOOOOOO  OOOOOOOOO"
echo " OO   OO   OO      OO      OOO                          OOO     OOO  OOO"
echo "OO     OO  OO      OO      OOO                          OOO     OOO   OOO"
echo "OOOOOOOOO  OO     OO       OOO                          OOO     OOO     OOO"
echo "OO     OO  OOOOOOOO        OOO                          OOO     OOO       OOO "
echo "OO     OO  OO     OO       OOO                          OOO     OOO        OOO "
echo "OO     OO  OO              OOO                          OOOOOOOOOOO  OOOOOOOOO"
echo "OO     OO  OO              OOO                           OOOOOOOOO   OOOOOOOO"
sleep 0.1
clear
echo ""
echo ""
echo ""
echo ""
echo "   OOO     OOOOOOOO    OOOOOOOOOOO                       OOOOOOOOO    OOOOOOOO"
echo "  OO OO    OOOOOOOOO   OOOOOOOOOOO                      OOOOOOOOOOO  OOOOOOOOO"
echo " OO   OO   OO      OO      OOO                          OOO     OOO  OOO"
echo "OO     OO  OO      OO      OOO                          OOO     OOO   OOO"
echo "OOOOOOOOO  OO     OO       OOO                          OOO     OOO     OOO"
echo "OO     OO  OOOOOOOO        OOO                          OOO     OOO       OOO "
echo "OO     OO  OO     OO       OOO                          OOO     OOO        OOO "
echo "OO     OO  OO      OO      OOO                          OOOOOOOOOOO  OOOOOOOOO"
echo "OO     OO  OO       OO     OOO                           OOOOOOOOO   OOOOOOOO"
sleep 0.1
clear
echo ""
echo ""
echo ""
echo ""
echo "   OOO     OOOOOOOO    OOOOOOOOOOO                       OOOOOOOOO    OOOOOOOO"
echo "  OO OO    OOOOOOOOO   OOOOOOOOOOO                      OOOOOOOOOOO  OOOOOOOOO"
echo " OO   OO   OO      OO      OOO                          OOO     OOO  OOO"
echo "OO     OO  OO      OO      OOO                          OOO     OOO   OOO"
echo "OOOOOOOOO  OO     OO       OOO                          OOO     OOO     OOO"
echo "OO     OO  OOOOOOOO        OOO                          OOO     OOO       OOO "
echo "OO     OO  OO     OO       OOO                          OOO     OOO        OOO "
echo "OO     OO  OO      OO      OOO                          OOOOOOOOOOO  OOOOOOOOO"
echo "OO     OO  OO       OO     OOO                           OOOOOOOOO   OOOOOOOO"
sleep 0.1
clear
echo ""
echo ""
echo ""
echo ""
echo "   OOO     OOOOOOOO    OOOOOOOOOOO                       OOOOOOOOO    OOOOOOOO"
echo "  OO OO    OOOOOOOOO   OOOOOOOOOOO                      OOOOOOOOOOO  OOOOOOOOO"
echo " OO   OO   OO      OO      OOO                          OOO     OOO  OOO"
echo "OO     OO  OO      OO      OOO                          OOO     OOO   OOO"
echo "OOOOOOOOO  OO     OO       OOO          OOO             OOO     OOO     OOO"
echo "OO     OO  OOOOOOOO        OOO                          OOO     OOO       OOO "
echo "OO     OO  OO     OO       OOO                          OOO     OOO        OOO "
echo "OO     OO  OO      OO      OOO                          OOOOOOOOOOO  OOOOOOOOO"
echo "OO     OO  OO       OO     OOO                           OOOOOOOOO   OOOOOOOO"
sleep 0.1
clear
echo ""
echo ""
echo ""
echo ""
echo "   OOO     OOOOOOOO    OOOOOOOOOOO                       OOOOOOOOO    OOOOOOOO"
echo "  OO OO    OOOOOOOOO   OOOOOOOOOOO                      OOOOOOOOOOO  OOOOOOOOO"
echo " OO   OO   OO      OO      OOO                          OOO     OOO  OOO"
echo "OO     OO  OO      OO      OOO                          OOO     OOO   OOO"
echo "OOOOOOOOO  OO     OO       OOO          OOO             OOO     OOO     OOO"
echo "OO     OO  OOOOOOOO        OOO                          OOO     OOO       OOO "
echo "OO     OO  OO     OO       OOO                          OOO     OOO        OOO "
echo "OO     OO  OO      OO      OOO                          OOOOOOOOOOO  OOOOOOOOO"
echo "OO     OO  OO       OO     OOO                           OOOOOOOOO   OOOOOOOO"
sleep 0.1
clear
echo ""
echo ""
echo ""
echo ""
echo "   OOO     OOOOOOOO    OOOOOOOOOOO                       OOOOOOOOO    OOOOOOOO"
echo "  OO OO    OOOOOOOOO   OOOOOOOOOOO                      OOOOOOOOOOO  OOOOOOOOO"
echo " OO   OO   OO      OO      OOO                          OOO     OOO  OOO"
echo "OO     OO  OO      OO      OOO          OOO             OOO     OOO   OOO"
echo "OOOOOOOOO  OO     OO       OOO          OOO             OOO     OOO     OOO"
echo "OO     OO  OOOOOOOO        OOO          OOO             OOO     OOO       OOO "
echo "OO     OO  OO     OO       OOO                          OOO     OOO        OOO "
echo "OO     OO  OO      OO      OOO                          OOOOOOOOOOO  OOOOOOOOO"
echo "OO     OO  OO       OO     OOO                           OOOOOOOOO   OOOOOOOO"
sleep 0.1
clear
echo ""
echo ""
echo ""
echo ""
echo "   OOO     OOOOOOOO    OOOOOOOOOOO                       OOOOOOOOO    OOOOOOOO"
echo "  OO OO    OOOOOOOOO   OOOOOOOOOOO                      OOOOOOOOOOO  OOOOOOOOO"
echo " OO   OO   OO      OO      OOO          OOO             OOO     OOO  OOO"
echo "OO     OO  OO      OO      OOO          OOO             OOO     OOO   OOO"
echo "OOOOOOOOO  OO     OO       OOO          OOO             OOO     OOO     OOO"
echo "OO     OO  OOOOOOOO        OOO          OOO             OOO     OOO       OOO "
echo "OO     OO  OO     OO       OOO          OOO             OOO     OOO        OOO "
echo "OO     OO  OO      OO      OOO                          OOOOOOOOOOO  OOOOOOOOO"
echo "OO     OO  OO       OO     OOO                           OOOOOOOOO   OOOOOOOO"
sleep 0.1
clear
echo ""
echo ""
echo ""
echo ""
echo "   OOO     OOOOOOOO    OOOOOOOOOOO                       OOOOOOOOO    OOOOOOOO"
echo "  OO OO    OOOOOOOOO   OOOOOOOOOOO      OOO             OOOOOOOOOOO  OOOOOOOOO"
echo " OO   OO   OO      OO      OOO          OOO             OOO     OOO  OOO"
echo "OO     OO  OO      OO      OOO          OOO             OOO     OOO   OOO"
echo "OOOOOOOOO  OO     OO       OOO          OOO             OOO     OOO     OOO"
echo "OO     OO  OOOOOOOO        OOO          OOO             OOO     OOO       OOO "
echo "OO     OO  OO     OO       OOO          OOO             OOO     OOO        OOO "
echo "OO     OO  OO      OO      OOO          OOO             OOOOOOOOOOO  OOOOOOOOO"
echo "OO     OO  OO       OO     OOO                           OOOOOOOOO   OOOOOOOO"
sleep 0.1
clear
echo ""
echo ""
echo ""
echo ""
echo "   OOO     OOOOOOOO    OOOOOOOOOOO      OOO              OOOOOOOOO    OOOOOOOO"
echo "  OO OO    OOOOOOOOO   OOOOOOOOOOO    OOOOOOO           OOOOOOOOOOO  OOOOOOOOO"
echo " OO   OO   OO      OO      OOO          OOO             OOO     OOO  OOO"
echo "OO     OO  OO      OO      OOO          OOO             OOO     OOO   OOO"
echo "OOOOOOOOO  OO     OO       OOO          OOO             OOO     OOO     OOO"
echo "OO     OO  OOOOOOOO        OOO          OOO             OOO     OOO       OOO "
echo "OO     OO  OO     OO       OOO          OOO             OOO     OOO        OOO "
echo "OO     OO  OO      OO      OOO        OOOOOOO           OOOOOOOOOOO  OOOOOOOOO"
echo "OO     OO  OO       OO     OOO          OOO              OOOOOOOOO   OOOOOOOO"
sleep 0.1
clear
echo ""
echo ""
echo ""
echo ""
echo "   OOO     OOOOOOOO    OOOOOOOOOOO    OOOOOOO            OOOOOOOOO    OOOOOOOO"
echo "  OO OO    OOOOOOOOO   OOOOOOOOOOO  OOOOOOOOOOO         OOOOOOOOOOO  OOOOOOOOO"
echo " OO   OO   OO      OO      OOO          OOO             OOO     OOO  OOO"
echo "OO     OO  OO      OO      OOO          OOO             OOO     OOO   OOO"
echo "OOOOOOOOO  OO     OO       OOO          OOO             OOO     OOO     OOO"
echo "OO     OO  OOOOOOOO        OOO          OOO             OOO     OOO       OOO "
echo "OO     OO  OO     OO       OOO          OOO             OOO     OOO        OOO "
echo "OO     OO  OO      OO      OOO      OOOOOOOOOOO         OOOOOOOOOOO  OOOOOOOOO"
echo "OO     OO  OO       OO     OOO        OOOOOOO            OOOOOOOOO   OOOOOOOO"
sleep 0.1
clear
echo "                                                  OOOO"
echo ""
echo ""
echo ""
echo "   OOO     OOOOOOOO    OOOOOOOOOOO  OOOOOOOOOOO          OOOOOOOOO    OOOOOOOO"
echo "  OO OO    OOOOOOOOO   OOOOOOOOOOO  OOOOOOOOOOO         OOOOOOOOOOO  OOOOOOOOO"
echo " OO   OO   OO      OO      OOO          OOO             OOO     OOO  OOO"
echo "OO     OO  OO      OO      OOO          OOO             OOO     OOO   OOO"
echo "OOOOOOOOO  OO     OO       OOO          OOO             OOO     OOO     OOO"
echo "OO     OO  OOOOOOOO        OOO          OOO             OOO     OOO       OOO "
echo "OO     OO  OO     OO       OOO          OOO             OOO     OOO        OOO "
echo "OO     OO  OO      OO      OOO      OOOOOOOOOOO         OOOOOOOOOOO  OOOOOOOOO"
echo "OO     OO  OO       OO     OOO      OOOOOOOOOOO          OOOOOOOOO   OOOOOOOO"
sleep 0.1
clear
echo "                                                   OO"
echo "                                                  OOOO"
echo "                                                  OOO"
echo ""
echo "   OOO     OOOOOOOO    OOOOOOOOOOO  OOOOOOOOOOO          OOOOOOOOO    OOOOOOOO"
echo "  OO OO    OOOOOOOOO   OOOOOOOOOOO  OOOOOOOOOOO         OOOOOOOOOOO  OOOOOOOOO"
echo " OO   OO   OO      OO      OOO          OOO             OOO     OOO  OOO"
echo "OO     OO  OO      OO      OOO          OOO             OOO     OOO   OOO"
echo "OOOOOOOOO  OO     OO       OOO          OOO             OOO     OOO     OOO"
echo "OO     OO  OOOOOOOO        OOO          OOO             OOO     OOO       OOO "
echo "OO     OO  OO     OO       OOO          OOO             OOO     OOO        OOO "
echo "OO     OO  OO      OO      OOO      OOOOOOOOOOO         OOOOOOOOOOO  OOOOOOOOO"
echo "OO     OO  OO       OO     OOO      OOOOOOOOOOO          OOOOOOOOO   OOOOOOOO"
sleep 0.1
clear
echo ""
echo ""
echo ""
echo "                                                    O"
echo "   OOO     OOOOOOOO    OOOOOOOOOOO  OOOOOOOOOOO    OO    OOOOOOOOO    OOOOOOOO"
echo "  OO OO    OOOOOOOOO   OOOOOOOOOOO  OOOOOOOOOOO   OOOO  OOOOOOOOOOO  OOOOOOOOO"
echo " OO   OO   OO      OO      OOO          OOO       OOOO  OOO     OOO  OOO"
echo "OO     OO  OO      OO      OOO          OOO             OOO     OOO   OOO"
echo "OOOOOOOOO  OO     OO       OOO          OOO             OOO     OOO     OOO"
echo "OO     OO  OOOOOOOO        OOO          OOO             OOO     OOO       OOO "
echo "OO     OO  OO     OO       OOO          OOO             OOO     OOO        OOO "
echo "OO     OO  OO      OO      OOO      OOOOOOOOOOO         OOOOOOOOOOO  OOOOOOOOO"
echo "OO     OO  OO       OO     OOO      OOOOOOOOOOO          OOOOOOOOO   OOOOOOOO"
sleep 0.1
clear
echo ""
echo ""
echo ""
echo ""
echo "   OOO     OOOOOOOO    OOOOOOOOOOO  OOOOOOOOOOO                OOOOOOOOO    OOOOOOOO"
echo "  OO OO    OOOOOOOOO   OOOOOOOOOOO  OOOOOOOOOOO    OO   OO    OOOOOOOOOOO  OOOOOOOOO"
echo " OO   OO   OO      OO      OOO          OOO         OO OO     OOO     OOO  OOO"
echo "OO     OO  OO      OO      OOO          OOO          OOO      OOO     OOO   OOO"
echo "OOOOOOOOO  OO     OO       OOO          OOO                   OOO     OOO     OOO"
echo "OO     OO  OOOOOOOO        OOO          OOO                   OOO     OOO       OOO "
echo "OO     OO  OO     OO       OOO          OOO                   OOO     OOO        OOO "
echo "OO     OO  OO      OO      OOO      OOOOOOOOOOO               OOOOOOOOOOO  OOOOOOOOO"
echo "OO     OO  OO       OO     OOO      OOOOOOOOOOO                OOOOOOOOO   OOOOOOOO"
sleep 0.1
clear
echo ""
echo ""
echo ""
echo ""
echo "   OOO     OOOOOOOO    OOOOOOOOOOO  OOOOOOOOOOO  OOOO     OOOO   OOOOOOOOO    OOOOOOOO"
echo "  OO OO    OOOOOOOOO   OOOOOOOOOOO  OOOOOOOOOOO     OO   OO     OOOOOOOOOOO  OOOOOOOOO"
echo " OO   OO   OO      OO      OOO          OOO          OO OO      OOO     OOO  OOO"
echo "OO     OO  OO      OO      OOO          OOO           OOO       OOO     OOO   OOO"
echo "OOOOOOOOO  OO     OO       OOO          OOO                     OOO     OOO     OOO"
echo "OO     OO  OOOOOOOO        OOO          OOO                     OOO     OOO       OOO "
echo "OO     OO  OO     OO       OOO          OOO                     OOO     OOO        OOO "
echo "OO     OO  OO      OO      OOO      OOOOOOOOOOO                 OOOOOOOOOOO  OOOOOOOOO"
echo "OO     OO  OO       OO     OOO      OOOOOOOOOOO                  OOOOOOOOO   OOOOOOOO"
sleep 0.1
clear
echo ""
echo ""
echo ""
echo ""
echo "   OOO     OOOOOOOO    OOOOOOOOOOO  OOOOOOOOOOO  OOOO     OOOO   OOOOOOOOO    OOOOOOOO"
echo "  OO OO    OOOOOOOOO   OOOOOOOOOOO  OOOOOOOOOOO  OO OO   OO OO  OOOOOOOOOOO  OOOOOOOOO"
echo " OO   OO   OO      OO      OOO          OOO      OO  OO OO  OO  OOO     OOO  OOO"
echo "OO     OO  OO      OO      OOO          OOO           OOO       OOO     OOO   OOO"
echo "OOOOOOOOO  OO     OO       OOO          OOO                     OOO     OOO     OOO"
echo "OO     OO  OOOOOOOO        OOO          OOO                     OOO     OOO       OOO "
echo "OO     OO  OO     OO       OOO          OOO                     OOO     OOO        OOO "
echo "OO     OO  OO      OO      OOO      OOOOOOOOOOO                 OOOOOOOOOOO  OOOOOOOOO"
echo "OO     OO  OO       OO     OOO      OOOOOOOOOOO                  OOOOOOOOO   OOOOOOOO"
sleep 0.1
clear
echo ""
echo ""
echo ""
echo ""
echo "   OOO     OOOOOOOO    OOOOOOOOOOO  OOOOOOOOOOO  OOOO     OOOO   OOOOOOOOO    OOOOOOOO"
echo "  OO OO    OOOOOOOOO   OOOOOOOOOOO  OOOOOOOOOOO  OO OO   OO OO  OOOOOOOOOOO  OOOOOOOOO"
echo " OO   OO   OO      OO      OOO          OOO      OO  OO OO  OO  OOO     OOO  OOO"
echo "OO     OO  OO      OO      OOO          OOO      OO   OOO   OO  OOO     OOO   OOO"
echo "OOOOOOOOO  OO     OO       OOO          OOO      OO    O    OO  OOO     OOO     OOO"
echo "OO     OO  OOOOOOOO        OOO          OOO      OO         OO  OOO     OOO       OOO "
echo "OO     OO  OO     OO       OOO          OOO      OO         OO  OOO     OOO        OOO "
echo "OO     OO  OO      OO      OOO      OOOOOOOOOOO                 OOOOOOOOOOO  OOOOOOOOO"
echo "OO     OO  OO       OO     OOO      OOOOOOOOOOO                  OOOOOOOOO   OOOOOOOO"
sleep 0.1
clear
echo ""
echo ""
echo ""
echo ""
echo "   OOO     OOOOOOOO    OOOOOOOOOOO  OOOOOOOOOOO  OOOO     OOOO   OOOOOOOOO    OOOOOOOO"
echo "  OO OO    OOOOOOOOO   OOOOOOOOOOO  OOOOOOOOOOO  OO OO   OO OO  OOOOOOOOOOO  OOOOOOOOO"
echo " OO   OO   OO      OO      OOO          OOO      OO  OO OO  OO  OOO     OOO  OOO"
echo "OO     OO  OO      OO      OOO          OOO      OO   OOO   OO  OOO     OOO   OOO"
echo "OOOOOOOOO  OO     OO       OOO          OOO      OO    O    OO  OOO     OOO     OOO"
echo "OO     OO  OOOOOOOO        OOO          OOO      OO         OO  OOO     OOO       OOO "
echo "OO     OO  OO     OO       OOO          OOO      OO         OO  OOO     OOO        OOO "
echo "OO     OO  OO      OO      OOO      OOOOOOOOOOO  OO         OO  OOOOOOOOOOO  OOOOOOOOO"
echo "OO     OO  OO       OO     OOO      OOOOOOOOOOO  OO         OO   OOOOOOOOO   OOOOOOOO"
sleep 0.1
